Feature: MeasureResource
  ...

  Scenario: Upload new XML measure
	Given I have a valid measure recording:
    """
    <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
    <measures>
    <measure>
      <source>no.muda.domain.Sist</source>
      <name>xmlRecording1</name>
      <value>12</value>
      <date>2010-11-08T01:28:24-08:00</date>
      <category>testSuite</category>
      <children>
        <measure>
          <source>no.muda.domain.KlassTest</source>
          <category>testCase</category>
          <name>shouldValidateNestedClasses</name>
          <value>1.0012</value>
          <date>2010-11-08T01:28:24-08:00</date>
          <failed>true</failed>
          <children></children>
        </measure>
        <measure>
          <source>no.muda.domain.KlassTest</source>
          <category>testCase</category>
          <name>shouldValidateUnNestedClasses</name>
          <value>1.0312</value>
          <date>2010-11-08T01:28:24-08:00</date>
          <failed>true</failed>
          <children></children>
        </measure>
      </children>
    </measure>
    <measure>
      <source>no.muda.domain.Midten</source>
      <name>xmlRecording2</name>
      <value>12</value>
      <date>2010-11-11T01:28:24-08:00</date>
      <category>testSuite</category>
      <children>
        <measure>
          <source>no.muda.domain.KlassTest</source>
          <category>testCase</category>
          <name>shouldValidateNestedClasses</name>
          <value>1.0012</value>
          <date>2010-11-11T01:28:24-08:00</date>
          <failed>true</failed>
          <children></children>
        </measure>
        <measure>
          <source>no.muda.domain.KlassTest</source>
          <category>testCase</category>
          <name>shouldValidateUnNestedClasses</name>
          <value>1.0312</value>
          <date>2010-11-11T01:28:24-08:00</date>
          <failed>false</failed>
          <children></children>
        </measure>
      </children>
    </measure>
    <measure>
      <source>no.muda.domain.Fyrst</source>
      <name>xmlRecording1</name>
      <value>12</value>
      <date>2010-11-11T01:28:24-08:00</date>
      <category>testSuite</category>
      <children>
        <measure>
          <source>no.muda.domain.KlassTest</source>
          <category>testCase</category>
          <name>shouldValidateNestedClasses</name>
          <value>1.0012</value>
          <date>2010-11-11T01:28:24-08:00</date>
          <failed>false</failed>
          <children></children>
        </measure>
        <measure>
          <source>no.muda.domain.KlassTest</source>
          <category>testCase</category>
          <name>shouldValidateUnNestedClasses</name>
          <value>1.0312</value>
          <date>2010-11-11T01:28:24-08:00</date>
          <failed>false</failed>
          <children></children>
        </measure>
      </children>
    </measure>
    </measures>
    """
    When I POST the measure recording as "application/xml" to "/measure"
    Then It should return status "200" OK
